# Generated by Django 5.0 on 2023-12-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
