# Generated by Django 5.0 on 2023-12-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
