# Generated by Django 5.0 on 2023-12-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_wallet_order_remove_returnedproduct_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='order',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Applied_coupon',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
