# Generated by Django 5.0 on 2023-12-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
